streamshub/console

- .eslintrc.cjs
- .storybook/main.ts
- .storybook/preview.ts
- package-lock.json
- package.json
- src/components/Table/ResponsiveTable.stories.tsx
- src/components/Table/TableView.stories.tsx
> setup storybook

- package-lock.json
**What this PR does / why we need it**:
> Update package-lock.json file.
**Which issue(s) this PR fixes**
> Replace this comment with references to related issues.
> e.g. `fixes #<issue number>`
**Verification steps**
> Attach a screenshot of the output.
> guidance on how to go the particular story.
> e.g. `point to the story with a text breadcrumb, something like "components > <component name> > <story name>”`
**Is there any work left / what's next** :
> Replace this comment with pending items that need to be covered in this PR or some pending items you are planning to do in the future PR.
**Special notes for your reviewer**:
> Update package lock json file

- .github/workflows/main.yml
- .github/workflows/storybook-to-pages.yml
**What this PR does / why we need it**:
> Fix failing GitHub action
**Which issue(s) this PR fixes**
> Replace this comment with references to related issues.
> e.g. `fixes #<issue number>`
**Verification steps**
> Attach a screenshot of the output.
> guidance on how to go the particular story.
> e.g. `point to the story with a text breadcrumb, something like "components > <component name> > <story name>”`
**Is there any work left / what's next** :
> Replace this comment with pending items that need to be covered in this PR or some pending items you are planning to do in the future PR.
**Special notes for your reviewer**:
> Fix failing GitHub action

- .github/workflows/storybook-to-pages.yml
**What this PR does / why we need it**:
> Fix failing storybook GitHub action
**Which issue(s) this PR fixes**
> Replace this comment with references to related issues.
> e.g. `fixes #<issue number>`
**Verification steps**
> Attach a screenshot of the output.
> guidance on how to go the particular story.
> e.g. `point to the story with a text breadcrumb, something like "components > <component name> > <story name>”`
**Is there any work left / what's next** :
> Replace this comment with pending items that need to be covered in this PR or some pending items you are planning to do in the future PR.
**Special notes for your reviewer**:
> Fix failing storybook GitHub action

- .github/gitops-config.json
- .github/project.yml
- .github/workflows/pre-release.yml
- .github/workflows/release.yml
Adds release action that pushes to quay.io and invokes renovate
> Initial import of release action

- .github/project.yml
- ui/Dockerfile
> Move Dockerfile to ubi9

- .github/project.yml
- ui/api/topics.tsx
- ui/app/[locale]/[authProfile]/@breadcrumbs/topics/[topic]/messages/page.tsx
- ui/app/[locale]/[authProfile]/@breadcrumbs/topics/[topic]/overview/page.tsx
> add the Message browser

- api/src/main/java/com/github/eyefloaters/console/api/service/RecordService.java
- api/src/test/java/com/github/eyefloaters/console/api/RecordsResourceIT.java
- api/src/test/java/com/github/eyefloaters/console/test/TopicHelper.java
> Prevent consumer seek before partition's beginning offset

- ui/app/[locale]/kafka/[kafkaId]/nodes/[nodeId]/configuration/ConfigTable.tsx
- ui/app/[locale]/kafka/[kafkaId]/topics/[topicId]/configuration/ConfigTable.tsx
- ui/app/[locale]/kafka/[kafkaId]/topics/[topicId]/configuration/NoResultsEmptyState.tsx
- ui/app/[locale]/kafka/[kafkaId]/topics/[topicId]/configuration/page.tsx
> Topic configuration

- api/src/main/java/com/github/eyefloaters/console/api/model/Topic.java
> Make `recordCount` and `totalLeaderLogBytes` supported topic sort fields

- api/src/main/java/com/github/eyefloaters/console/api/model/DataListResponse.java
- api/src/main/java/com/github/eyefloaters/console/api/model/DataResponse.java
- api/src/main/java/com/github/eyefloaters/console/api/model/ErrorResponse.java
- api/src/main/java/com/github/eyefloaters/console/api/model/JsonApiDocument.java
- api/src/main/java/com/github/eyefloaters/console/api/model/KafkaCluster.java
- api/src/main/java/com/github/eyefloaters/console/api/model/ListFetchParams.java
- api/src/main/java/com/github/eyefloaters/console/api/model/Topic.java
- api/src/main/java/com/github/eyefloaters/console/api/service/RecordService.java
- api/src/main/java/com/github/eyefloaters/console/api/support/ListRequestContext.java
- api/src/main/java/com/github/eyefloaters/console/api/support/SizeLimitedSortedSet.java
- api/src/test/java/com/github/eyefloaters/console/api/TopicsResourceIT.java
> Add missing pagination links and current page number to list responses

- api/src/main/java/com/github/eyefloaters/console/api/TopicsResource.java
- api/src/main/java/com/github/eyefloaters/console/api/model/JsonApiDocument.java
- api/src/main/java/com/github/eyefloaters/console/api/service/ConfigService.java
- api/src/main/java/com/github/eyefloaters/console/api/service/TopicService.java
- api/src/main/java/com/github/eyefloaters/console/api/support/OASModelFilter.java
- api/src/main/resources/openapi/examples/createTopic-configs.json
- api/src/main/resources/openapi/examples/createTopic-simple.json
- api/src/main/resources/openapi/examples/createTopic-validateOnly.json
- api/src/main/resources/openapi/examples/patchTopic-simple.json
- api/src/main/resources/openapi/examples/patchTopic-validateOnly.json
- api/src/test/java/com/github/eyefloaters/console/api/TopicsResourceIT.java
Closes #78 
~~Built on #77, this will be re-based once merged.~~
> Allow dry run validation for createTopic and patchTopic operations

- ui/api/topics.ts
- ui/app/[locale]/kafka/[kafkaId]/topics/create/ConfigTable.tsx
- ui/app/[locale]/kafka/[kafkaId]/topics/create/CreateTopic.tsx
- ui/app/[locale]/kafka/[kafkaId]/topics/create/Errors.tsx
- ui/app/[locale]/kafka/[kafkaId]/topics/create/FieldName.tsx
- ui/app/[locale]/kafka/[kafkaId]/topics/create/FieldPartitions.tsx
- ui/app/[locale]/kafka/[kafkaId]/topics/create/FieldReplicas.tsx
- ui/app/[locale]/kafka/[kafkaId]/topics/create/StepDetails.tsx
- ui/app/[locale]/kafka/[kafkaId]/topics/create/StepOptions.tsx
- ui/app/[locale]/kafka/[kafkaId]/topics/create/StepReview.tsx
- ui/app/[locale]/kafka/[kafkaId]/topics/create/createErrorToFieldError.ts
- ui/app/[locale]/kafka/[kafkaId]/topics/create/page.tsx
> Options validation

- ui/api/topics.ts
- ui/app/[locale]/NextIntlProvider.tsx
- ui/app/[locale]/kafka/[kafkaId]/@modal/default.tsx
- ui/app/[locale]/kafka/[kafkaId]/@modal/topics/[topicId]/delete/DeleteTopicModal.tsx
- ui/app/[locale]/kafka/[kafkaId]/@modal/topics/[topicId]/delete/page.tsx
- ui/app/[locale]/kafka/[kafkaId]/nodes/NodesTable.tsx
- ui/app/[locale]/kafka/[kafkaId]/nodes/[nodeId]/configuration/ConfigTable.tsx
- ui/app/[locale]/kafka/[kafkaId]/topics/TopicsTable.tsx
- ui/app/[locale]/kafka/[kafkaId]/topics/[topicId]/configuration/ConfigTable.tsx
- ui/app/[locale]/kafka/[kafkaId]/topics/[topicId]/configuration/page.tsx
- ui/app/[locale]/kafka/[kafkaId]/topics/create/CreateTopic.tsx
- ui/app/[locale]/kafka/[kafkaId]/topics/create/Errors.tsx
- ui/app/[locale]/kafka/[kafkaId]/topics/create/StepDetails.tsx
- ui/app/[locale]/kafka/[kafkaId]/topics/create/StepOptions.tsx
- ui/app/[locale]/kafka/[kafkaId]/topics/create/StepReview.tsx
- ui/app/[locale]/kafka/[kafkaId]/topics/create/topicMutateErrorToFieldError.ts
- ui/app/[locale]/kafka/[kafkaId]/topics/page.tsx
- ui/components/DeleteModal.stories.tsx
- ui/components/DeleteModal.test.tsx
- ui/components/DeleteModal.tsx
- ui/components/table/ResponsiveTable.stories.tsx
- ui/components/table/ResponsiveTable.tsx
- ui/components/table/TableView.stories.tsx
- ui/messages/en.json
> Delete topic modal

- ui/app/[locale]/kafka/[kafkaId]/topics/TopicsTable.tsx
- ui/app/[locale]/kafka/[kafkaId]/topics/page.tsx
> Can't sort by consumer groups or partitions (yet)

- ui/api/topics.ts
- ui/app/[locale]/kafka/[kafkaId]/topics/TopicsTable.tsx
- ui/app/[locale]/kafka/[kafkaId]/topics/page.tsx
- ui/components/table/TableView.tsx
- ui/utils/useFilterParams.ts
> Use the pagination links for the topics table

- ui/app/[locale]/kafka/[kafkaId]/topics/(page)/TopicsTable.tsx
> Link the topic name in the table

- api/src/main/java/com/github/eyefloaters/console/api/model/NewTopic.java
- api/src/test/java/com/github/eyefloaters/console/api/TopicsResourceIT.java
> fix: validate new topic name is not blank

- ui/app/[locale]/SessionRefresher.tsx
- ui/app/[locale]/layout.tsx
- ui/components/Quickstarts/HelpContainer.tsx
Also, wrap the quickstart imports to catch SSR related errors
> Perform the session refresh only after mounting the component

- api/src/main/java/com/github/eyefloaters/console/api/Annotations.java
- api/src/main/java/com/github/eyefloaters/console/api/KafkaClustersResource.java
- api/src/main/java/com/github/eyefloaters/console/api/model/KafkaCluster.java
- api/src/main/java/com/github/eyefloaters/console/api/model/KafkaListener.java
- api/src/main/java/com/github/eyefloaters/console/api/service/KafkaClusterService.java
- api/src/main/java/com/github/eyefloaters/console/api/support/ListRequestContext.java
- api/src/test/java/com/github/eyefloaters/console/api/KafkaClustersResourceIT.java
- ui/api/kafka/schema.ts
Return all listeners unless annotated as hidden.
> Multiple Kafka cluster listeners

- ui/api/kafka/actions.ts
- ui/api/kafka/ranges.promql.ts
- ui/api/kafka/schema.ts
- ui/app/[locale]/kafka/[kafkaId]/overview/ChartCpuUsage.tsx
- ui/app/[locale]/kafka/[kafkaId]/overview/ChartMemoryUsage.tsx
- ui/app/[locale]/kafka/[kafkaId]/overview/ChartSkeletonLoader.tsx
- ui/app/[locale]/kafka/[kafkaId]/overview/ClusterChartsCard.tsx
- ui/app/[locale]/kafka/[kafkaId]/overview/chartConsts.ts
- ui/app/[locale]/kafka/[kafkaId]/overview/page.tsx
- ui/global.d.ts
- ui/utils/format.ts
Also finalise the layout, add proper titles and tooltips.
> Charts are by broker, show the ranges as stacked areas

- ui/api/kafka/actions.ts
- ui/api/kafka/schema.ts
- ui/app/[locale]/AppLayout.tsx
- ui/app/[locale]/AppLayoutProvider.tsx
- ui/app/[locale]/ClusterConnectionDetails.tsx
- ui/app/[locale]/ClusterDrawer.tsx
- ui/app/[locale]/ClusterDrawerContext.tsx
- ui/app/[locale]/ClusterDrawerProvider.tsx
- ui/app/[locale]/home/ClustersTable.tsx
- ui/app/[locale]/kafka/[kafkaId]/@header/overview/ConnectButton.tsx
- ui/app/[locale]/kafka/[kafkaId]/@header/overview/page.tsx
- ui/app/[locale]/kafka/[kafkaId]/KafkaSwitcher.tsx
- ui/components/ExpandableSection.tsx
- ui/components/ExternalLink.tsx
> Connection details drawer

- api/src/main/java/com/github/eyefloaters/console/api/ConsumerGroupsResource.java
- api/src/main/java/com/github/eyefloaters/console/api/model/ConsumerGroupFilterParams.java
- api/src/main/java/com/github/eyefloaters/console/api/model/OffsetAndMetadata.java
- api/src/main/java/com/github/eyefloaters/console/api/service/ConsumerGroupService.java
- api/src/main/java/com/github/eyefloaters/console/api/support/FetchFilterPredicate.java
- api/src/main/java/com/github/eyefloaters/console/api/support/ListRequestContext.java
- api/src/test/java/com/github/eyefloaters/console/api/ConsumerGroupsResourceIT.java
- ui/api/consumerGroups/actions.ts
- ui/api/consumerGroups/schema.ts
- ui/app/[locale]/kafka/[kafkaId]/consumer-groups/ConsumerGroupsTable.tsx
- ui/app/[locale]/kafka/[kafkaId]/consumer-groups/[groupId]/LagTable.tsx
- ui/app/[locale]/kafka/[kafkaId]/consumer-groups/[groupId]/MembersTable.tsx
Also support consumer group ID (name) and state filtering on list operation
> Limit consumer group API calls to page, add log end offset to describe

- ui/api/topics/actions.ts
- ui/api/topics/schema.ts
- ui/app/[locale]/kafka/[kafkaId]/@header/topics/[topicId]/TopicHeader.tsx
- ui/app/[locale]/kafka/[kafkaId]/topics/[topicId]/partitions/NoResultsEmptyState.tsx
- ui/app/[locale]/kafka/[kafkaId]/topics/[topicId]/partitions/PartitionsTable.tsx
- ui/components/table/TableView.tsx
> Update topic partitions

- api/src/main/java/com/github/eyefloaters/console/api/model/Topic.java
- api/src/main/java/com/github/eyefloaters/console/api/service/TopicService.java
- api/src/main/java/com/github/eyefloaters/console/api/support/ListRequestContext.java
- ui/api/topics/schema.ts
- ui/app/[locale]/kafka/[kafkaId]/@header/topics/page.tsx
> Return topic list status summary in meta, update UI icons

- ui/api/kafka/actions.ts
- ui/api/kafka/cluster.promql.ts
- ui/api/kafka/kpi.promql.ts
- ui/api/kafka/schema.ts
- ui/app/[locale]/AppLayout.tsx
- ui/app/[locale]/kafka/[kafkaId]/@activeBreadcrumb/nodes/[nodeId]/NodeBreadcrumb.tsx
- ui/app/[locale]/kafka/[kafkaId]/@activeBreadcrumb/nodes/page.tsx
- ui/app/[locale]/kafka/[kafkaId]/@header/nodes/[nodeId]/NodeHeader.tsx
- ui/app/[locale]/kafka/[kafkaId]/@header/nodes/page.tsx
- ui/app/[locale]/kafka/[kafkaId]/nodes/DistributionChart.tsx
- ui/app/[locale]/kafka/[kafkaId]/nodes/NodesTable.tsx
- ui/app/[locale]/kafka/[kafkaId]/nodes/page.tsx
All references to "Nodes" should have been renamed to "Brokers" as well.
> Update nodes page

- ui/app/[locale]/AppLayout.tsx
- ui/app/[locale]/ClusterDrawer.tsx
> Remove @patternfly/quickstart HelpContainer

- ui/app/[locale]/kafka/[kafkaId]/nodes/DistributionChart.tsx
> Add an "All" option to the partitions distribution chart

- ui/app/[locale]/kafka/[kafkaId]/nodes/NodesTable.tsx
> Improve spacing in the broker details expanded row

- ui/app/[locale]/kafka/[kafkaId]/nodes/NodesTable.tsx
It will be reintroduced when we'll support KRaft mode
> Remove the controller label from the brokers page

- ui/api/kafka/actions.ts
> Order Kafka clusters by name

- ui/app/[locale]/kafka/[kafkaId]/topics/[topicId]/messages/_components/DateTimePicker.tsx
- ui/app/[locale]/kafka/[kafkaId]/topics/[topicId]/messages/_components/FilterGroup.tsx
> Fix message browser toolbar when switching between filter types. 

- ui/app/[locale]/kafka/[kafkaId]/topics/[topicId]/messages/page.tsx
> Fix the messages page crashing the app when navigating back to it from a link

- ui/app/[locale]/kafka/[kafkaId]/topics/[topicId]/messages/_components/FilterGroup.tsx
- ui/app/[locale]/kafka/[kafkaId]/topics/[topicId]/messages/_components/PartitionSelector.tsx
> Auto-close dropdowns when clicking outside them

- ui/app/[locale]/kafka/[kafkaId]/overview/page.tsx
It could happen for Prometheus to be out of sync or not yet up to date. We sanitize the numbers to avoid showing impossible figures.
Fixes problems like:
> Ensure topics KPIs are never less than 0

- api/src/main/java/com/github/eyefloaters/console/api/service/KafkaClusterService.java
- api/src/test/java/com/github/eyefloaters/console/api/KafkaClustersResourceIT.java
> Filter out unconfigured Kafka clusters from listing

- api/pom.xml
> Manage nimbus-jose-jwt version to v9.37.2

- ui/app/[locale]/kafka/[kafkaId]/nodes/[nodeId]/configuration/ConfigTable.tsx
> Fix cell keys in the broker's config table

- ui/app/[locale]/home/page.tsx
- ui/app/[locale]/kafka/[kafkaId]/@header/consumer-groups/[groupId]/page.tsx
- ui/app/[locale]/kafka/[kafkaId]/@header/overview/page.tsx
- ui/app/[locale]/kafka/[kafkaId]/consumer-groups/[groupId]/LagTable.tsx
- ui/app/[locale]/kafka/[kafkaId]/consumer-groups/[groupId]/MembersTable.tsx
- ui/app/[locale]/kafka/[kafkaId]/nodes/NodesTable.tsx
- ui/app/[locale]/kafka/[kafkaId]/topics/[topicId]/partitions/NoResultsEmptyState.tsx
- ui/app/[locale]/kafka/[kafkaId]/topics/[topicId]/partitions/PartitionsTable.tsx
- ui/components/ClusterOverview/TopicChartsCard.tsx
- ui/components/ClusterOverview/TopicsPartitionsCard.tsx
- ui/components/TopicsTable/TopicsTable.tsx
- ui/messages/en.json
Migrate All Leftover Text to i18n Translation Files
> Migrate All Leftover Text to i18n Translation Files

- README.md
Update symbol for Apache Kafka in README
> Update symbol for Apache Kafka in README

- ui/app/[locale]/home/ClustersTable.stories.tsx
- ui/app/[locale]/home/ClustersTable.tsx
- ui/app/[locale]/home/TopicsTable.stories.tsx
- ui/app/[locale]/home/TopicsTable.tsx
- ui/app/[locale]/kafka/[kafkaId]/consumer-groups/ConsumerGroupsTable.stories.tsx
- ui/app/[locale]/kafka/[kafkaId]/consumer-groups/[groupId]/LagTable.stories.tsx
- ui/app/[locale]/kafka/[kafkaId]/consumer-groups/[groupId]/MembersTable.stories.tsx
- ui/app/[locale]/kafka/[kafkaId]/consumer-groups/[groupId]/MembersTable.tsx
- ui/app/[locale]/kafka/[kafkaId]/layout.tsx
- ui/app/[locale]/kafka/[kafkaId]/nodes/NodesTable.tsx
- ui/app/[locale]/kafka/[kafkaId]/nodes/nodesTable.stories.tsx
- ui/app/[locale]/kafka/[kafkaId]/topics/[topicId]/partitions/NoResultsEmptyState.stories.tsx
- ui/app/[locale]/kafka/[kafkaId]/topics/[topicId]/partitions/PartitionsTable.stories.tsx
- ui/app/[locale]/kafka/[kafkaId]/topics/[topicId]/partitions/PartitionsTable.tsx
- ui/app/[locale]/kafka/[kafkaId]/topics/create/CreateTopic.stories.tsx
- ui/app/[locale]/kafka/[kafkaId]/topics/create/FieldName.stories.tsx
- ui/app/[locale]/kafka/[kafkaId]/topics/create/FieldName.tsx
- ui/app/[locale]/kafka/[kafkaId]/topics/create/FieldPartition.stories.tsx
- ui/app/[locale]/kafka/[kafkaId]/topics/create/FieldPartitions.tsx
- ui/app/[locale]/kafka/[kafkaId]/topics/create/FieldReplicas.stories.tsx
- ui/app/[locale]/kafka/[kafkaId]/topics/create/FieldReplicas.tsx
- ui/app/[locale]/kafka/[kafkaId]/topics/create/ReviewTable.tsx
- ui/app/[locale]/kafka/[kafkaId]/topics/create/StepOptions.tsx
- ui/app/[locale]/kafka/[kafkaId]/topics/create/StepReview.tsx
- ui/messages/en.json
- ui/tests/playwright/HomePage.test.tsx
>  Adding Stories for Components

- ui/tests/playwright/HomePage.test.tsx
The PR will fix the failing playwright github action
> fix failing test

- api/pom.xml
3.8.x is the next LTS after 3.2.x
> Bump quarkus.version from 3.2.12.Final to 3.8.4

- .github/gitops-config.json
- .github/workflows/integration.yml
- .github/workflows/release.yml
- ui/.dockerignore
- ui/Dockerfile
Also correct reference to environments repo
> Build UI direct in action, simplify UI Dockerfile, fix API release args

- ui/api/kafka/actions.ts
- ui/api/kafka/topic.promql.ts
> Support node pool topic metrics

- ui/app/[locale]/AppLayout.tsx
- ui/app/[locale]/ClusterConnectionDetails.tsx
- ui/app/[locale]/ClusterDrawer.tsx
- ui/app/[locale]/kafka/[kafkaId]/topics/(page)/ConnectedTopicsTable.tsx
- ui/app/[locale]/layout.tsx
- ui/components/TopicsTable/TopicsTable.tsx
- ui/components/TopicsTable/components/EmptyStateNoTopics.tsx
- ui/environment.d.ts
- ui/utils/env.ts
pre-pended PRODUCTIZED_BUILD with NEXT_PUBLIC_
> pre-pended PRODUCTIZED_BUILD with NEXT_PUBLIC_

- .github/dependabot.yml
Combines playwright updates. I.e., reduce dependabot PRs like #951 and #952
> Add `playwright` dependabot group

- .github/workflows/integration.yml
- .github/workflows/release.yml
- .github/workflows/snapshot.yml
- api/src/main/java/com/github/streamshub/console/api/support/TrustAllCertificateManager.java
- operator/bin/modify-bundle-metadata.sh
- operator/src/main/resources/application.properties
- obtain default image tag from label
- skip all previous versions for snapshot and CI builds
- add host name to info log message
- add namespace variable to generate K8s resources
- attach generate K8s resource to builds and releases
> operator: obtain default image tag from label

- ui/app/[locale]/(public)/(home)/page.tsx
use a simple card instead of an expandable card
> use simple card instead of expandable card

- .github/workflows/integration.yml
- .github/workflows/snapshot.yml
This will also be cherry-picked to branch `0.3.x`.
> Run integration and snapshot jobs on non-feature branches

- .github/workflows/playwright-tests.yml
- pom.xml
- ui/.gitignore
Bump to the next Quarkus LTS release
---
Bumps `quarkus.platform.version` from 3.8.6 to 3.15.1.
Updates `io.quarkus.platform:quarkus-maven-plugin` from 3.8.6 to 3.15.1
<details>
<summary>Commits</summary>
<ul>
<li><a href="https://github.com/quarkusio/quarkus-platform/commit/7fae50aff64567d00157ce07f89cd297eff07a5e"><code>7fae50a</code></a> [maven-release-plugin] prepare release 3.15.1</li>
<li><a href="https://github.com/quarkusio/quarkus-platform/commit/a6489e1ebeb4e33ae3eb749601f5d66662432a2b"><code>a6489e1</code></a> Merge pull request <a href="https://redirect.github.com/quarkusio/quarkus-platform/issues/1307">#1307</a> from gsmet/quarkus-3.15.1</li>
<li><a href="https://github.com/quarkusio/quarkus-platform/commit/29f0a44673d92d4f6ad156a869cfcbe7d29e7660"><code>29f0a44</code></a> …
> Bump quarkus.platform.version from 3.8.6 to 3.15.1

- ui/package-lock.json
- ui/package.json
Backport updates to Next.js dependencies for 0.3.6.
> Backport 0.3.6

- ui/app/[locale]/(authorized)/kafka/[kafkaId]/@header/nodes/page.tsx
- ui/components/Navigation/NavItemLink.tsx
fix (issue)[https://github.com/streamshub/console/issues/1120]
> fix: When the Rebalance tab is selected, the Brokers tab keeps the appearance of being selected as well.

- ui/api/kafka/schema.ts
- ui/app/[locale]/(authorized)/kafka/[kafkaId]/@header/overview/ConnectButton.tsx
- ui/app/[locale]/(authorized)/kafka/[kafkaId]/@header/overview/page.tsx
feat: hide pause button when Kafka cluster is unmanaged
> feat: hide pause button when Kafka cluster is unmanaged

- .github/project.yml
Retry #1163 with fix from #1164
> Release 0.4.0 (attempt 2)

- .github/workflows/integration.yml
- .github/workflows/release.yml
- .github/workflows/snapshot.yml
This PR introduces support for the ppc64le architecture, extending the project's usability across multiple architectures.
> Enable ppc64le architecture support

- .github/workflows/integration.yml
- .github/workflows/release.yml
- .github/workflows/snapshot.yml
> fix: Disable network access during build of operator catalog

- api/src/main/java/com/github/streamshub/console/api/support/ListRequestContext.java
- api/src/test/java/com/github/streamshub/console/api/TopicsResourceIT.java
- ui/api/topics/actions.ts
- ui/app/[locale]/(authorized)/kafka/[kafkaId]/topics/(page)/page.tsx
Fix the pagination issue in Topic table
> Fix pagination issue in topic table

- ui/app/[locale]/(authorized)/kafka/[kafkaId]/nodes/nodesTable.stories.tsx
fix node table story
related to [issue](https://github.com/streamshub/console/issues/1265)
> fix node table story

- ui/app/[locale]/(authorized)/SessionRefresher.tsx
- ui/components/AppMasthead.tsx
- ui/components/ClusterOverview/components/useChartWidth.tsx
fix lint warnings
related to https://github.com/streamshub/console/issues/1287
> fix lint warnings

- ui/app/[locale]/(authorized)/kafka/[kafkaId]/topics/[topicId]/partitions/PartitionsTable.tsx
- ui/utils/usePagination.ts
Add pagination for Partition Table
Related to issue https://github.com/streamshub/console/issues/1249
> Add pagination for Partition Table

- ui/components/MessagesTable/MessagesTable.tsx
fix the buggy row in the message browser
related to [issue1286](https://github.com/streamshub/console/issues/1286)
> fix buggy row in message browser

- ui/app/[locale]/(authorized)/kafka/[kafkaId]/@header/overview/ConnectButton.tsx
- ui/app/[locale]/(authorized)/kafka/[kafkaId]/@header/overview/page.tsx
- ui/app/[locale]/(authorized)/kafka/[kafkaId]/overview/ConnectedClusterCard.tsx
- ui/components/ClusterOverview/ClusterCard.stories.tsx
- ui/components/ClusterOverview/ClusterCard.tsx
- ui/components/ClusterOverview/ReconciliationPauseButton.tsx
- ui/components/ClusterOverview/components/ErrorsAndWarnings.tsx
- ui/messages/en.json
- Move Reconciliation Pause Button to Kafka Details Card
- Remove 'Total' from Topic and Partition in Topic Overview Card
- Hide Error/Warning Labels When No Alerts
> Move Reconciliation pause button to kafka details card

- .github/workflows/release.yml
- api/pom.xml
- common/pom.xml
- operator/bin/release-prepare.sh
- operator/pom.xml
- operator/src/main/olm/bundles/streamshub-console-operator.v.yaml
- operator/src/main/olm/bundles/streamshub-console-operator.v0.6.0.yaml
- operator/src/main/olm/channel.alpha.yaml
- pom.xml
- ui/pom.xml
- Fix operator bundle release
- Set project version for micro-release 0.6.1
> fix operator bundle release handling

- .github/workflows/integration.yml
- .github/workflows/release.yml
- .github/workflows/snapshot.yml
This PR introduces support for the s390x architecture, to extend the project's usability across multiple architectures.
> S390x support

- ui/app/[locale]/(authorized)/kafka/[kafkaId]/@header/consumer-groups/[groupId]/reset-offset/page.tsx
- ui/app/[locale]/(authorized)/kafka/[kafkaId]/consumer-groups/[groupId]/reset-offset/Dryrun.tsx
- ui/app/[locale]/(authorized)/kafka/[kafkaId]/consumer-groups/[groupId]/reset-offset/ResetOffset.tsx
- ui/messages/en.json
- Add spacing between the topic cards
- Remove Jump links if the number of topics is less than or equal to 3 
- fix jump links not working issue
> Bug fixes in Dryrun page

- .github/workflows/integration.yml
- .github/workflows/release.yml
- .github/workflows/snapshot.yml
- Makefile
- operator/src/main/resources/com/github/streamshub/console/dependents/console.deployment.yaml
- ui/Dockerfile
- ui/environment.d.ts
- ui/utils/env.ts
Update the "read-only" env variable name
> Update the "read-only" env variable name 

- ui/components/ClusterOverview/ClusterCard.tsx
- ui/components/ClusterOverview/ReconciliationModal.tsx
- ui/components/ClusterOverview/ReconciliationPauseButton.tsx
- ui/components/ReconciliationPausedBanner.tsx
- ui/messages/en.json
Add confirmation prompt to resume reconciliation
Update Pause reconciliation text
> Add confirmation prompt to resume reconciliation

- ui/messages/en.json
Update reconciliation paused warning
> Update reconciliation paused warning

- ui/app/[locale]/(authorized)/kafka/[kafkaId]/consumer-groups/[groupId]/reset-offset/ResetConsumerOffset.tsx
- ui/app/[locale]/(authorized)/kafka/[kafkaId]/consumer-groups/[groupId]/reset-offset/dryrun/ConnectedDryrunPage.tsx
- ui/app/[locale]/(authorized)/kafka/[kafkaId]/consumer-groups/[groupId]/reset-offset/dryrun/Dryrun.tsx
- ui/app/[locale]/(authorized)/kafka/[kafkaId]/nodes/rebalances/ConnectedRebalancesTable.tsx
Remove Double padding in consumer group reset offset and rebalance page
> Remove Double padding in consumer group reset offset andrebalance page

- ui/components/MessagesTable/components/MessageDetails.tsx
- ui/messages/en.json
Add header for Schema link section
> Add header for Schema link section

- ui/app/[locale]/(authorized)/kafka/[kafkaId]/consumer-groups/ConsumerGroupsTable.tsx
- ui/app/[locale]/(authorized)/kafka/[kafkaId]/nodes/[nodeId]/configuration/ConfigTable.tsx
- ui/app/[locale]/(authorized)/kafka/[kafkaId]/nodes/rebalances/RebalanceTable.tsx
- ui/app/[locale]/(authorized)/kafka/[kafkaId]/topics/[topicId]/configuration/ConfigTable.tsx
- ui/app/[locale]/(authorized)/kafka/[kafkaId]/topics/[topicId]/partitions/PartitionsTable.tsx
- ui/components/Table/Toolbar/ChipFilter/ChipFilter.tsx
- ui/components/Table/Toolbar/ChipFilter/components/FilterCheckbox.tsx
- ui/components/Table/Toolbar/ChipFilter/storybookHelpers.tsx
- ui/components/Table/Toolbar/ChipFilter/types.ts
- ui/components/TopicsTable/TopicsTable.tsx
Add description text to checkbox selection option as the kRaft changes require description text in the checkbox selection option
> Add description text to checkbox selection option

- ui/api/rebalance/actions.ts
- ui/api/rebalance/schema.ts
- ui/app/[locale]/(authorized)/kafka/[kafkaId]/nodes/rebalances/RebalanceTable.tsx
- ui/app/[locale]/(authorized)/kafka/[kafkaId]/nodes/rebalances/page.tsx
- ui/messages/en.json
Display the date/time each KafkaRebalance status was last updated, according to the CR status condition.
> Display last updated date/time for Kafka Rebalance resources

- api/src/main/java/com/github/streamshub/console/api/service/NodeService.java
- api/src/test/java/com/github/streamshub/console/api/NodesResourceIT.java
- ui/api/nodes/schema.ts
> Include lead controller Id always in nodes list response

- api/src/main/java/com/github/streamshub/console/api/service/ConfigService.java
- api/src/main/java/com/github/streamshub/console/api/support/OASModelFilter.java
- api/src/test/java/com/github/streamshub/console/LoggingConfigWatcherTest.java
- api/src/test/java/com/github/streamshub/console/api/ConsumerGroupsResourceIT.java
- api/src/test/java/com/github/streamshub/console/api/KafkaClustersResourceIT.java
- api/src/test/java/com/github/streamshub/console/api/KafkaClustersResourceMetricsIT.java
- api/src/test/java/com/github/streamshub/console/api/KafkaClustersResourceNoK8sIT.java
- api/src/test/java/com/github/streamshub/console/api/KafkaClustersResourceOidcIT.java
- api/src/test/java/com/github/streamshub/console/api/RecordsResourceIT.java
- api/src/test/java/com/github/streamshub/console/api/TopicsResourceIT.java
- api/src/test/java/com/github/streamshub/console/api/TopicsResourceOidcIT.java
- api/src/test/java/com/github/streamshub/console/api/support/EnabledOperationFilterTest.java
- api/src/test/java/com/github/streamshub/console/api/support/OASModelFilterTest.java
- api/src/test/java/com/github/streamshub/console/api/support/UuidValidatorTest.java
- api/src/test/java/com/github/streamshub/console/kafka/systemtest/utils/ConsumerUtils.java
- api/src/test/java/com/github/streamshub/console/test/RecordHelper.java
- api/src/test/java/com/github/streamshub/console/test/TopicHelper.java
- operator/src/main/java/com/github/streamshub/console/ReconciliationException.java
- operator/src/main/java/com/github/streamshub/console/dependents/ConsoleResource.java
- operator/src/main/java/com/github/streamshub/console/dependents/support/ConfigSupport.java
Resolve a number of issues/code smells identified by Sonar. Also includes a fix to the config retrieval service to fix the sorting of properties by key.
> fix: resolve sonar issues, correct unsorted configs response

- ui/api/nodes/actions.ts
- ui/api/nodes/schema.ts
- ui/app/[locale]/(authorized)/kafka/[kafkaId]/nodes/ConnectedNodesTable.tsx
- ui/app/[locale]/(authorized)/kafka/[kafkaId]/nodes/DistributionChart.stories.tsx
- ui/app/[locale]/(authorized)/kafka/[kafkaId]/nodes/DistributionChart.tsx
- ui/app/[locale]/(authorized)/kafka/[kafkaId]/nodes/NodesLabel.tsx
- ui/app/[locale]/(authorized)/kafka/[kafkaId]/nodes/NodesTable.tsx
- ui/app/[locale]/(authorized)/kafka/[kafkaId]/nodes/nodesTable.stories.tsx
- ui/app/[locale]/(authorized)/kafka/[kafkaId]/nodes/page.tsx
- ui/components/Table/Toolbar/ChipFilter/ChipFilter.tsx
- ui/components/Table/Toolbar/ChipFilter/components/FilterGroupedCheckbox.tsx
- ui/components/Table/Toolbar/ChipFilter/components/index.ts
- ui/components/Table/Toolbar/ChipFilter/index.ts
- ui/components/Table/Toolbar/ChipFilter/types.ts
- ui/messages/en.json
> feat: UI changes for KRaft

- api/src/test/java/com/github/streamshub/console/api/ConsumerGroupsResourceIT.java
- api/src/test/java/com/github/streamshub/console/api/KafkaClustersResourceIT.java
- api/src/test/java/com/github/streamshub/console/api/KafkaClustersResourceMetricsIT.java
- api/src/test/java/com/github/streamshub/console/api/KafkaClustersResourceNoK8sIT.java
- api/src/test/java/com/github/streamshub/console/api/KafkaClustersResourceOidcIT.java
- api/src/test/java/com/github/streamshub/console/api/KafkaRebalancesResourceIT.java
- api/src/test/java/com/github/streamshub/console/api/KafkaRebalancesResourceOidcIT.java
- api/src/test/java/com/github/streamshub/console/api/NodesResourceIT.java
- api/src/test/java/com/github/streamshub/console/api/RecordsResourceIT.java
- api/src/test/java/com/github/streamshub/console/api/TopicsResourceIT.java
- api/src/test/java/com/github/streamshub/console/api/TopicsResourceOidcIT.java
- api/src/test/java/com/github/streamshub/console/kafka/systemtest/utils/ClientsConfig.java
- api/src/test/java/com/github/streamshub/console/kafka/systemtest/utils/ConsumerUtils.java
- api/src/test/java/com/github/streamshub/console/test/RecordHelper.java
- api/src/test/java/com/github/streamshub/console/test/TestHelper.java
- api/src/test/java/com/github/streamshub/console/test/TopicHelper.java
Also remove vestiges of OAuth test connection support
> fix: minimize metadata age limit in test client (help flaky tests)

- .github/project.yml
Release 0.6.5 from branch `0.6.x`
> Release 0.6.5

- ui/components/AppMasthead.tsx
fix(branding): add leading slash to logo src path
> fix(branding): add leading slash to logo src path

- ui/api/api.ts
- ui/api/kafka/actions.ts
- ui/api/kafka/schema.ts
- ui/app/[locale]/(public)/(home)/ConnectedClustersTable.tsx
- ui/app/[locale]/(public)/(home)/page.tsx
- ui/app/[locale]/(public)/kafka/[kafkaId]/login/page.tsx
- ui/app/api/auth/[...nextauth]/auth-options.ts
- ui/components/ClustersTable.stories.tsx
- ui/components/ClustersTable.tsx
Same as #1657, backported to `0.6.x`
> feat: Add pagination to list of kafka cluster

- README.md
Update the documentation link to the Prometheus operator
> Update the documentation link to the Prometheus operator

- api/README.md
> Update Api Readme

- api/src/main/java/com/github/streamshub/console/api/KafkaClustersResource.java
- api/src/main/java/com/github/streamshub/console/api/model/KafkaClusterFilterParams.java
- api/src/main/java/com/github/streamshub/console/api/service/KafkaClusterService.java
- api/src/test/java/com/github/streamshub/console/api/KafkaClustersResourceIT.java
- ui/api/kafka/actions.ts
- ui/app/[locale]/(public)/(home)/ConnectedClustersTable.tsx
- ui/app/[locale]/(public)/(home)/page.tsx
- ui/components/ClustersTable.tsx
Add support for filtering Kafka clusters by name
>  Add support for filtering Kafka clusters by name

- ui/app/[locale]/(authorized)/kafka/[kafkaId]/topics/create/CreateTopic.tsx
Fix the gap issue in the create topic
> Fix the gap issue in the create topic

- ui/app/[locale]/(authorized)/kafka/[kafkaId]/@activeBreadcrumb/consumer-groups/[groupId]/page.tsx
- ui/app/[locale]/(authorized)/kafka/[kafkaId]/@activeBreadcrumb/consumer-groups/[groupId]/reset-offset/dryrun/page.tsx
- ui/app/[locale]/(authorized)/kafka/[kafkaId]/@activeBreadcrumb/consumer-groups/[groupId]/reset-offset/page.tsx
- ui/app/[locale]/(authorized)/kafka/[kafkaId]/@activeBreadcrumb/consumer-groups/page.tsx
- ui/app/[locale]/(authorized)/kafka/[kafkaId]/@activeBreadcrumb/nodes/[nodeId]/NodeBreadcrumb.tsx
- ui/app/[locale]/(authorized)/kafka/[kafkaId]/@activeBreadcrumb/nodes/page.tsx
- ui/app/[locale]/(authorized)/kafka/[kafkaId]/@activeBreadcrumb/nodes/rebalances/page.tsx
- ui/app/[locale]/(authorized)/kafka/[kafkaId]/@activeBreadcrumb/overview/page.tsx
- ui/app/[locale]/(authorized)/kafka/[kafkaId]/@activeBreadcrumb/topics/[topicId]/TopicBreadcrumb.tsx
- ui/app/[locale]/(authorized)/kafka/[kafkaId]/@activeBreadcrumb/topics/create/page.tsx
- ui/app/[locale]/(authorized)/kafka/[kafkaId]/@activeBreadcrumb/topics/page.tsx
- ui/app/[locale]/(authorized)/kafka/[kafkaId]/@header/overview/page.tsx
- ui/app/[locale]/(authorized)/kafka/[kafkaId]/layout.tsx
- ui/app/[locale]/(public)/kafka/[kafkaId]/login/SignInPage.tsx
- ui/app/[locale]/(public)/kafka/[kafkaId]/login/page.tsx
- ui/components/AppDropdown.stories.tsx
- ui/components/AppDropdown.tsx
- ui/components/AppLayout.tsx
- ui/components/AppMasthead.tsx
- ui/messages/en.json
1. Added a searchable dropdown to the overview page to allow navigation between Kafka clusters.
2.  Updated the Breadcrumb component to include a link to the Home page.
3. Modified the Login page to align with the new workflow.
> feat: Update streams console navigation

- docs/sources/modules/proc-logging-in.adoc
Updates the logging in content to reflect new cluster filter
> docs(overview): updates the cluster overview page for new filter

- api/pom.xml
- api/src/main/java/com/github/streamshub/console/api/service/TopicService.java
- api/src/test/java/com/github/streamshub/console/api/TopicsResourceIT.java
- operator/pom.xml
- Diagnose/fix flaky test around creating a managed topic
- Migrate from deprecated surefire/failsafe configuration properties
- Remove empty properties on Quarkus plugin
> Testing updates

- ui/app/[locale]/(authorized)/kafka/[kafkaId]/consumer-groups/ConsumerGroupsTable.tsx
- ui/components/Table/Toolbar/ChipFilter/components/FilterSwitcher.tsx
[In the consumer group T](fix: prevent truncation of labels in consumer group table and filter dropdown
> fix truncated values

- ui/components/ReconciliationProvider.tsx
Avoid unnecessary re-rendering using useCallback and useMemo
> Avoid unnecessary re-rendering using useCallback and useMemo

- ui/app/[locale]/(public)/kafka/[kafkaId]/login/SignInPage.tsx
Replace t.rich with RichText element
> Replace t.rich with RichText element

- docs/sources/assemblies/assembly-deploying.adoc
- docs/sources/attributes.adoc
- docs/sources/modules/deploying/ref-authentication-options.adoc
- docs/sources/modules/deploying/ref-metrics-options.adoc
- docs/sources/modules/deploying/ref-schema-registries.adoc
Adds new schema registries config section.
Updates config sections for metrics and oidc for authentication options
> docs(console): adds config for schema registries

- docs/sources/modules/deploying/proc-connecting-console.adoc
- docs/sources/modules/deploying/proc-deploying-kafka.adoc
- docs/sources/modules/deploying/ref-authentication-options.adoc
- docs/sources/modules/deploying/ref-metrics-options.adoc
- docs/sources/modules/deploying/ref-schema-registries.adoc
Updates the install paths in the console doc
> docs(install): updates paths to install files

- .github/workflows/snapshot.yml
Refine Quay image tagging for branches and add expiration
> Refine Quay image tagging for branches and add expiration

- api/src/main/java/com/github/streamshub/console/api/service/KafkaClusterService.java
- api/src/test/java/com/github/streamshub/console/api/KafkaClustersResourceIT.java
Get kafka version from spec when Reconciliation is paused
> Get kafka version from spec when Reconciliation is paused

- ui/components/MessagesTable/components/AdvancedSearch.tsx
- ui/components/MessagesTable/components/FromGroup.tsx
- ui/components/MessagesTable/components/MessagesTableToolbar.tsx
- ui/components/MessagesTable/components/UntilGroup.tsx
fix: prevent offset=0 from defaulting to latest in advanced search
Adjust layout to increase form width in toolbar
handle switching between live mode and message limit correctly
> Fix multiple bugs in the message filter

- systemtests/config.yaml
- systemtests/src/main/java/com/github/streamshub/systemtests/Environment.java
- systemtests/src/main/java/com/github/streamshub/systemtests/clients/KafkaClients.java
- systemtests/src/main/java/com/github/streamshub/systemtests/constants/TimeConstants.java
- systemtests/src/main/java/com/github/streamshub/systemtests/interfaces/ExtensionContextParameterResolver.java
- systemtests/src/main/java/com/github/streamshub/systemtests/setup/strimzi/KafkaSetup.java
- systemtests/src/main/java/com/github/streamshub/systemtests/utils/FileUtils.java
- systemtests/src/main/java/com/github/streamshub/systemtests/utils/WaitUtils.java
- systemtests/src/main/java/com/github/streamshub/systemtests/utils/playwright/PwUtils.java
- systemtests/src/main/java/com/github/streamshub/systemtests/utils/resourceutils/KafkaTopicUtils.java
- systemtests/src/main/java/com/github/streamshub/systemtests/utils/resourceutils/NamespaceUtils.java
- systemtests/src/main/java/com/github/streamshub/systemtests/utils/testchecks/TopicChecks.java
- systemtests/src/test/java/com/github/streamshub/systemtests/AbstractST.java
- systemtests/src/test/java/com/github/streamshub/systemtests/KafkaST.java
- systemtests/src/test/java/com/github/streamshub/systemtests/MessagesST.java
- systemtests/src/test/java/com/github/streamshub/systemtests/TopicST.java
This PR adds fixes found during test execution. Changes should remove flakiness from the tests.
> [ST] Fixes for flaky asserts, updates to the YAML installation, add pull secret option to test clients

- examples/console-config.yaml
Console api was not able to start due to these errors.
> fix(examples): update console config to use proper objects

- api/src/main/java/com/github/streamshub/console/api/security/AuthorizationInterceptor.java
- api/src/main/java/com/github/streamshub/console/api/security/ConsoleAuthenticationMechanism.java
- api/src/main/java/com/github/streamshub/console/api/security/ConsolePermission.java
- api/src/main/java/com/github/streamshub/console/api/security/PermissionCache.java
- api/src/main/java/com/github/streamshub/console/api/security/PermissionService.java
- api/src/main/java/com/github/streamshub/console/api/service/KafkaClusterService.java
- api/src/main/java/com/github/streamshub/console/api/support/KafkaContext.java
- api/src/main/resources/application.properties
- api/src/test/java/com/github/streamshub/console/api/KafkaClustersResourceIT.java
- api/src/test/java/com/github/streamshub/console/api/TopicsResourceIT.java
- api/src/test/java/com/github/streamshub/console/api/TopicsResourceOidcIT.java
> fix: account for Kafka namespace in security/audit config & processing

- ui/app/[locale]/(authorized)/kafka/[kafkaId]/topics/[topicId]/configuration/ConfigTable.tsx
- ui/tests/playwright/ConsumerGroupsPage.test.tsx
- ui/tests/playwright/ConsumerPage.test.tsx
- ui/tests/playwright/MessagesPage.test.tsx
- ui/tests/playwright/NodePropertyPage.test.tsx
- ui/tests/playwright/NodesPage.test.tsx
- ui/tests/playwright/PartitionsPage.test.tsx
- ui/tests/playwright/TopicConfigurationPage.test.tsx
- ui/tests/playwright/auth.setup.ts
- ui/tests/playwright/authenticated-page.ts
- ui/tests/playwright/authenticated-test.ts
- ui/tests/playwright/playwright.config.ts
- Correct topic configuration `ariaLabel`
- Remove superfluous nav to overview page in fixture
- Attempt to improve use of locators and expectations
> Improve playwright tests, reduce flakes

- api/src/main/java/com/github/streamshub/console/api/ClientFactory.java
- api/src/main/java/com/github/streamshub/console/api/security/AuthorizationInterceptor.java
- api/src/main/java/com/github/streamshub/console/api/security/ConsoleAuthenticationMechanism.java
- api/src/main/java/com/github/streamshub/console/api/security/ConsolePermission.java
- api/src/main/java/com/github/streamshub/console/api/security/PermissionCache.java
- api/src/main/java/com/github/streamshub/console/api/security/PermissionService.java
- api/src/main/java/com/github/streamshub/console/api/service/KafkaClusterService.java
- api/src/main/java/com/github/streamshub/console/api/support/KafkaContext.java
- api/src/main/resources/application.properties
- api/src/test/java/com/github/streamshub/console/api/KafkaClustersResourceIT.java
- api/src/test/java/com/github/streamshub/console/api/TopicsResourceIT.java
- api/src/test/java/com/github/streamshub/console/api/TopicsResourceOidcIT.java
- common/src/main/java/com/github/streamshub/console/config/KafkaClusterConfig.java
- common/src/main/java/com/github/streamshub/console/config/security/ResourceTypes.java
- examples/console-config.yaml
- examples/console/console-security-oidc.yaml
Individual commits link to associated PRs on `main`.
> [0.8.x] Backport fixes from main for 0.8.6

- ui/app/[locale]/(authorized)/kafka/[kafkaId]/consumer-groups/ConsumerGroupsTable.stories.tsx
This change was missed in PR #1893
> fix: adjust consumer group table story for new groupId attribute

- ui/app/[locale]/(authorized)/kafka/[kafkaId]/kafka-connect/[...connectorId]/ConnectorDetails.stories.tsx
- ui/app/[locale]/(authorized)/kafka/[kafkaId]/kafka-connect/[...connectorId]/ConnectorDetails.tsx
Add Storybook stories for ConnectorDetails component in Kafka Connect
> Add Storybook stories for ConnectorDetails component in Kafka Connect

- api/src/main/java/com/github/streamshub/console/api/security/ConsolePermission.java
- api/src/main/java/com/github/streamshub/console/api/security/PermissionCache.java
- api/src/main/java/com/github/streamshub/console/api/service/NodeService.java
- api/src/test/java/com/github/streamshub/console/api/KafkaClustersResourceIT.java
- api/src/test/java/com/github/streamshub/console/api/NodesResourceIT.java
- common/src/main/java/com/github/streamshub/console/config/security/RuleConfig.java
- common/src/test/java/com/github/streamshub/console/config/security/RuleConfigTest.java
- examples/console/console-security-oidc.yaml
- operator/src/main/java/com/github/streamshub/console/api/v1alpha1/spec/security/Rule.java
> Add support for RegEx resource names (authZ), enforce node list authZ

- ui/app/[locale]/(authorized)/kafka/[kafkaId]/consumer-groups/ConsumerGroupsTable.tsx
- ui/app/[locale]/(authorized)/kafka/[kafkaId]/topics/[topicId]/consumer-groups/ConsumerGroupsTable.stories.tsx
- ui/app/[locale]/(authorized)/kafka/[kafkaId]/topics/[topicId]/consumer-groups/ConsumerGroupsTable.tsx
Add icons for consumer group state
> Add icons for consumer group state

- ui/app/[locale]/(authorized)/kafka/[kafkaId]/layout.tsx
- ui/components/AppDropdown.stories.tsx
- ui/components/AppDropdown.tsx
- ui/components/AppLayout.tsx
- ui/components/AppMasthead.tsx
Hide authentication description in MenuItem when OIDC is enabled
> hide authentication description in MenuItem when OIDC is enabled
