- api/src/main/java/com/github/eyefloaters/console/api/TopicsResource.java
- api/src/main/java/com/github/eyefloaters/console/api/model/Either.java
- api/src/main/java/com/github/eyefloaters/console/api/model/PartitionInfo.java
- api/src/main/java/com/github/eyefloaters/console/api/model/Topic.java
- api/src/main/java/com/github/eyefloaters/console/api/service/TopicService.java
- api/src/test/java/com/github/eyefloaters/console/api/TopicsResourceIT.java
- ui/api/bookmarks.ts
- ui/api/topics.ts
- ui/api/types.ts
- ui/components/topicPage.tsx
Sample response with all offsets included for the partition.
```json
{
"data": {
"id": "s0QDg0v1Q16m4QqQDvJEPQ",
"type": "topics",
"attributes": {
"name": "__strimzi-topic-operator-kstreams-topic-store-changelog",
"internal": false,
"partitions": [
{
"partition": 0,
"leader": {
"id": 0,
"host": "broker-0.cluster-a.192.168.39.252.nip.io",
"port": 443
},
"replicas": [
{
"id": 0,
"host": "broker-0.cluster-a.192.168.39.252.nip.io",
"port": 443
}
],
"isr": [
{
"id": 0,
"host": "broker-0.cluster-a.192.168.39.252.nip.io",
"port": 443
}
],
"offsets": {
"earliest": {
"offset": 0,
"leaderEpoch": 0
},
"latest": {
"offset": 5,
"leaderEpoch": 0
},
"maxTimestamp": {
"offset": 4,
"timestamp": "2023-09-07T18:02:17.546Z",
"leaderEpoch": 0
},
"timestamp": {
"offset": 0,
"timestamp": …
```
> Return and display multiple offsets, calculate number of records

- ui/components/Bytes.tsx
- ui/components/Number.tsx
Several areas of the topic/partition page display dashes when there is a defined value 0.
Current:
From https://github.com/eyefloaters/console/issues/60#issue-1933132684
This PR displays a defined number whenever one is present, like below:
> Display any defined number value

- ui/api/topics.ts
- ui/app/[locale]/kafka/[kafkaId]/(root)/KafkaBreadcrumbItem.tsx
- ui/app/[locale]/kafka/[kafkaId]/(root)/brokers/BrokersTable.tsx
- ui/app/[locale]/kafka/[kafkaId]/(root)/layout.tsx
- ui/app/[locale]/kafka/[kafkaId]/KafkaSwitcher.tsx
- ui/app/[locale]/kafka/[kafkaId]/page.tsx
- ui/app/[locale]/kafka/[kafkaId]/topics/[topicId]/KafkaBreadcrumbItem.tsx
- ui/app/[locale]/kafka/[kafkaId]/topics/[topicId]/layout.tsx
- ui/app/[locale]/kafka/[kafkaId]/topics/[topicId]/page.tsx
Reordered tabs a bit, prioritising those that I feel are going the most commonly used ones by devs:
- Topics, when in a Cluster
- Messages, when in a Topic
For tabs that show a countable information I added a label with the count. This way you can enter a topic and see how many partitions it has without having to click the tab
The cluster switcher takes you to a different page depending on where you interacted with it:
- if inside one of the Cluster pages (Topics, Brokers, etc) it takes you to the same page for the new cluster
- if inside any other section, it will take you to the parent page. Eg. if you are browsing a specific topic, switching cluster will take you to the Topics page for that cluster
> Quality of life changes

- .github/dependabot.yml
As shown by https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/about-dependabot-version-updates#supported-repositories-and-ecosystems, pnpm should be using `npm` as the `package-ecosystem` for dependabot's configuration.
> fix: use package-ecosystem `npm` for pnpm updates

- ui/api/messages.ts
- ui/app/[locale]/kafka/[kafkaId]/topics/[topicId]/messages/ConnectedMessagesTable.tsx
- ui/app/[locale]/kafka/[kafkaId]/topics/[topicId]/messages/_components/MessagesTable.tsx
- ui/app/[locale]/kafka/[kafkaId]/topics/[topicId]/messages/page.tsx
- ui/app/[locale]/kafka/[kafkaId]/topics/[topicId]/messages/parseSearchParams.ts
This also makes the details drawer persistent, so the URL should be safer to share with others.
In the screen a message with a lot of data, scrolled down a bit.
> Truncate values in the messages list, retrieve up to 50k of data when checking a message details

- api/src/main/java/com/github/eyefloaters/console/api/Annotations.java
- api/src/main/java/com/github/eyefloaters/console/api/TopicsResource.java
- api/src/main/java/com/github/eyefloaters/console/api/model/Topic.java
- api/src/main/java/com/github/eyefloaters/console/api/model/TopicFilterParams.java
- api/src/main/java/com/github/eyefloaters/console/api/service/TopicService.java
- api/src/main/java/com/github/eyefloaters/console/api/support/FetchFilterPredicate.java
- api/src/main/java/com/github/eyefloaters/console/api/support/ListRequestContext.java
- api/src/test/java/com/github/eyefloaters/console/api/TopicsResourceIT.java
- ui/api/topics/actions.ts
- ui/api/topics/schema.ts
Closes #37 
Adds support for filtering topics by `id`, `name`, and `visibility`. "Internal" topics (those starting with `_`) are hidden by default any may be un-hidden by using `filter[visibility]=eq,internal` or `filter[visibility]=in,internal,external`.
Topic name filter supports `eq`, `in`, or `like` operations where `like` follows the Unix glob patterns. `*` allows any character, zero or more times; and `?` allows any single character.
> Add filters to listTopics for `id`, `name`, and `visibility`

- ui/api/topics/actions.ts
- ui/api/topics/schema.ts
- ui/app/[locale]/kafka/[kafkaId]/@header/topics/page.tsx
- ui/app/[locale]/kafka/[kafkaId]/topics/(page)/EmptyStateNoTopics.tsx
- ui/app/[locale]/kafka/[kafkaId]/topics/(page)/TopicsTable.tsx
- ui/app/[locale]/kafka/[kafkaId]/topics/(page)/page.tsx
- ui/components/table/EmptyStateNoMatchFound.tsx
- ui/components/table/TableView.tsx
- ui/components/tableToolbar/ChipFilter/ChipFilter.tsx
- ui/components/tableToolbar/ChipFilter/components/FilterCheckbox.tsx
- ui/components/tableToolbar/ChipFilter/components/FilterSearch.tsx
- ui/utils/useFilterParams.ts
Update the Topics page header to be in sync with the designs. The warning icon will always show zero as for the moment we don't have the count of topics that are in-sync and under replicated.
Connect the search input to search in the topic names.
Add a switch to show/hide internal topics (hide is the default). not in sync. Part of #165.
Add a status column to show the in-sync or under replicated state of a topic. This is done by looking for a replica amongst all partitions that hold the topic that is flagged as not in sync.
Reorder the columns.
Change the "Edit properties" action to "Edit configuration". Part of #142.
Change the column name "Messages" to "Record count".
Add the right empty states for when there are no topics and for when a search doesn't produce results.
> Align the topics page to the designs

- ui/app/[locale]/kafka/[kafkaId]/topics/[topicId]/messages/_components/ColumnsModal.tsx
- ui/app/[locale]/kafka/[kafkaId]/topics/[topicId]/messages/_components/MessagesTable.tsx
- ui/components/table/ResponsiveTable.tsx
Adds a "Manage columns" link in the Message browser toolbar
Clicking it will show a modal where the user can manage the visible columns
Any selection performed there will be persisted on the browser's local storage. Refreshing (or revisiting) the page will keep the previously selected columns. The setting is global for the message browser, it's not specific to a particular topic.
> Allow selecting columns to see in the message browser

- ui/app/[locale]/kafka/[kafkaId]/topics/(page)/TopicsTable.tsx
Fix offline topic status appearance, as discussed in https://github.com/eyefloaters/console/pull/219#issuecomment-1853395070
> Use danger color and exclamation-circle icon for offline topic status

- .github/dependabot.yml
- .github/workflows/dependabot-auto.yml
- .github/workflows/release.yml
This will only auto-approve/auto-merge patch releases. Minor and major updates still require a dev's approval and merge.
> Set milestone on dependabot PRs, approve and merge patch updates

- ui/api/topics/actions.ts
- ui/api/topics/schema.ts
- ui/app/[locale]/kafka/[kafkaId]/topics/(page)/TopicsTable.tsx
- ui/app/[locale]/kafka/[kafkaId]/topics/(page)/page.tsx
- ui/components/tableToolbar/ChipFilter/ChipFilter.tsx
- ui/components/tableToolbar/ChipFilter/components/FilterSelect.tsx
- ui/components/tableToolbar/ChipFilter/components/FilterSwitcher.tsx
- ui/components/tableToolbar/ChipFilter/components/index.ts
- ui/components/tableToolbar/ChipFilter/types.ts
- ui/utils/useFilterParams.ts
> Add a way to filter topics by status

- api/src/main/java/com/github/eyefloaters/console/api/RecordsResource.java
- api/src/main/java/com/github/eyefloaters/console/api/model/KafkaRecord.java
- api/src/main/java/com/github/eyefloaters/console/api/service/RecordService.java
- ui/api/messages/actions.ts
- ui/api/messages/schema.ts
- ui/app/[locale]/kafka/[kafkaId]/topics/[topicId]/messages/_components/ColumnsModal.tsx
- ui/app/[locale]/kafka/[kafkaId]/topics/[topicId]/messages/_components/MessageDetails.tsx
- ui/app/[locale]/kafka/[kafkaId]/topics/[topicId]/messages/_components/MessagesTable.tsx
- ui/messages/en.json
Added "size" column with tooltip:
> Add message size with tooltip, use variable polling duration

- ui/api/consumerGroups/actions.ts
- ui/api/consumerGroups/schema.ts
- ui/api/kafka/actions.ts
- ui/api/kafka/schema.ts
- ui/app/[locale]/kafka/[kafkaId]/consumer-groups/ConsumerGroupsTable.tsx
- ui/app/[locale]/kafka/[kafkaId]/consumer-groups/[groupId]/MembersTable.tsx
- ui/app/[locale]/kafka/[kafkaId]/overview/page.tsx
Also fix display of consumer group assignments when empty:
> Map consumer group counts and Kafka conditions to cluster overview

- .github/dependabot.yml
In theory this should give us 1 storybook dependabot PR instead of 7 per day :laughing: 
Reference: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#groups
> Group storybook dependabot updates

- ui/api/kafka/kpi.promql.ts
- ui/api/kafka/schema.ts
- ui/app/[locale]/kafka/[kafkaId]/nodes/page.tsx
- ui/app/[locale]/kafka/[kafkaId]/overview/ChartIncomingOutgoing.tsx
- ui/app/[locale]/kafka/[kafkaId]/overview/page.tsx
1. Make the UI a bit more tolerant of missing metric values which may not be available in Prometheus early in the deployment.
2. Using `kafka_server_replicamanager_partitioncount` [1] for the number of partition replicas on each broker.
Before: 
After: 
[1] https://www.ibm.com/docs/en/instana-observability/current?topic=technologies-monitoring-kafka#partitions
> Tolerate missing metrics, use alternate metric from replica count

- ui/app/[locale]/kafka/not-found.tsx
- ui/components/ButtonLink.tsx
- ui/components/table/ResponsiveTable.tsx
Fixes #477 
For some reason the Button from PatternFly was causing the component to re-render endlessly, breaking the underlying link. I removed the component and made the link look like a Button using the proper PF classes.
> Replace Button from PF to a plain link with the Button's css classes applied

- install/003-install-console.sh
This pull request addresses an issue where the `tr` command encountering an "Illegal byte sequence" error when attempting to generate a random string from `/dev/urandom`. The issue is typically related to locale settings when using MacOS.
> [install] MacOS modify creation of console secrets

- api/.checkstyle/checkstyle.xml
- api/src/main/java/com/github/eyefloaters/console/api/service/TopicService.java
- api/src/main/java/com/github/eyefloaters/console/api/support/InformerFactory.java
- api/src/test/java/com/github/eyefloaters/console/api/TopicsResourceIT.java
- ui/api/topics/schema.ts
- ui/app/[locale]/kafka/[kafkaId]/@header/topics/[topicId]/TopicHeader.tsx
- ui/app/[locale]/kafka/[kafkaId]/topics/(page)/TopicsTable.tsx
- ui/app/components/ManagedTopicLabel.tsx
Added a "Managed" indicator to the topic status in the listing, just to demonstrate the data is available. A topic is managed when there is a corresponding `KafkaTopic` CR in Kubernetes.
Also added to subtitle for topic details, but I couldn't figure out how to add an icon...
> Initial support for managed KafkaTopic resources

- api/src/main/java/com/github/eyefloaters/console/api/model/KafkaCluster.java
- api/src/main/java/com/github/eyefloaters/console/api/service/KafkaClusterService.java
- api/src/test/java/com/github/eyefloaters/console/api/KafkaClustersResourceIT.java
- ui/api/kafka/schema.ts
- ui/app/[locale]/AppLayout.tsx
- ui/app/[locale]/home/ClustersTable.tsx
- ui/app/[locale]/home/page.tsx
Fixes #543 
Changes:
- links disabled for Kafka clusters without connection configuration
- broker/consumer groups show _Connection not configured_ rather than details
- Clusters excluded from the navigation
Sample
> fix: identify configured and un-configured Kafka clusters

- ui/app/[locale]/AppLayout.tsx
- ui/app/[locale]/AppMasthead.tsx
- ui/components/TechPreviewPopover.stories.tsx
- ui/components/TechPreviewPopover.tsx
> Add a Tech Preview banner and relative UI elements

- .github/workflows/playwright-test.yml
Make the PW workflow run on pull_request_target only for PRs marked as 'safe to test' or for PRs coming from dependabot
> Fix PW workflow

- ui/app/[locale]/kafka/[kafkaId]/consumer-groups/ConsumerGroupsTable.tsx
As we use the consumer group id as a url fragment, we need to escape it to avoid problematic characters (like .) 
Fixes #633
> Escape the consumer group id

- api/src/main/java/com/github/eyefloaters/console/api/support/InformerFactory.java
- api/src/test/java/com/github/eyefloaters/console/api/TopicsResourceIT.java
> Default name of TopicName to metadata.name when spec.topicName absent

- ui/.dockerignore
- ui/Dockerfile
> Ensure runtime defaults for LOG_LEVEL and CONSOLE_MODE

- ui/api/kafka/actions.ts
- ui/app/[locale]/kafka/[kafkaId]/nodes/DistributionChart.tsx
- ui/app/[locale]/kafka/[kafkaId]/nodes/NodesTable.tsx
- ui/app/[locale]/kafka/[kafkaId]/nodes/page.tsx
- ui/app/[locale]/kafka/[kafkaId]/overview/page.tsx
- ui/app/api/auth/[...nextauth]/keycloak.ts
- ui/components/ClusterOverview/ClusterCard.tsx
- ui/environment.d.ts
- ui/messages/en.json
- ui/utils/authOptions.ts
- ui/utils/logger.ts
- ui/utils/session.ts
Make some take an implicit default; make Prometheus optional showing fallbacks in the UI
For example, the brokers page will show a warning
The cluster overview page will show placeholders
> Change the required env variables

- ui/messages/en.json
Fix typo in the translation file for topic metrics
> Fix typo in the translation file for topic metrics

- ui/components/TopicsTable/TopicsTable.tsx
- ui/components/TopicsTable/components/EmptyStateNoTopics.stories.tsx
- ui/components/TopicsTable/components/EmptyStateNoTopics.tsx
- ui/messages/en.json
> Allow for showing internal topics from the empty state when no topics exist

- .github/workflows/storybook.yml
Disabling the JSON index seems to fix the problem
Fixes #785
> Fix test-storybook failing against remote urls

- ui/app/[locale]/kafka/[kafkaId]/nodes/DistributionChart.stories.tsx
- ui/app/[locale]/kafka/[kafkaId]/nodes/DistributionChart.tsx
- ui/messages/en.json
Update Brokers distribution chart legends to show the number/ percentages
Fixes [issue#359](https://github.com/eyefloaters/console/issues/359) 
storybook story
> Update Brokers distribution chart legends to show the number/ percentages

- api/src/main/java/com/github/streamshub/console/api/KafkaClustersResource.java
- api/src/main/java/com/github/streamshub/console/api/model/KafkaCluster.java
- api/src/main/java/com/github/streamshub/console/api/service/KafkaClusterService.java
- api/src/test/java/com/github/streamshub/console/api/KafkaClustersResourceIT.java
- install/002-deploy-console-kafka.sh
- install/README.md
- install/resources/kafka/console-kafka-zk.kafka.yaml
- install/resources/kafka/console-nodepool.kafkanodepool.yaml
- ui/api/kafka/actions.ts
- ui/api/kafka/cluster.promql.ts
- ui/api/kafka/kpi.promql.ts
- ui/api/kafka/schema.ts
- ui/components/ClusterOverview/components/ChartDiskUsage.tsx
With Strimzi KafkaNodePools [1] (required to run the cluster in KRaft mode), storage metrics have a slightly different format for the PVC label. This PR adds support for storage allocated via a node pool, and also changes the example Kafka cluster to use KRaft mode.
[1] https://strimzi.io/blog/2023/08/28/kafka-node-pools-storage-and-scheduling/
> Use KRaft for example install, support node pool storage metrics

- .github/workflows/integration.yml
- .github/workflows/snapshot.yml
- Makefile
- operator/bin/common.sh
- operator/bin/generate-catalog.sh
- operator/bin/modify-bundle-metadata.sh
- operator/src/main/java/com/github/streamshub/console/ConsoleReconciler.java
This PR fixes errors with operator display page/sidebar in openshift UI. Also it adds new fields such as creation timestamp, support, certified, categories, repository link, operator image sha etc. The procedure of creating a catalog image with such fields is following -> First a CSV yaml file is created from CSVMetadata annotation using operator-sdk. Then it's placeholder values are replaced using yq and skopeo (both need to be installed) and a catalog image is created.
> [OLM] Fix operator UI and add new fields for operator

- .github/workflows/integration.yml
- .github/workflows/release.yml
- .github/workflows/snapshot.yml
- operator/bin/modify-bundle-metadata.sh
This PR fixes some minor issues where images were being tagged with uppercase, while catalog was created with lower case image tag. This resulted in images missing in registry and back-off errors during operator deployment.
> [CI] Fix and unify image tags to lowercase, fix cut on localhost

- api/pom.xml
- api/src/main/resources/application.properties
- operator/pom.xml
- operator/src/main/resources/application.properties
Resolve errors in the API logs about unknown `quarkus.container-image.labels.*` properties. These properties apply at build time only, so this PR uses a `build` profile to apply them only at that time. Additionally, this resolves a warning about the Strimzi API classes not being present in the Jandex index.
Warning for unknown runtime properties:
```
2024-07-18 14:53:42,089 WARN  [io.qua.config] (Quarkus Main Thread) Unrecognized configuration key "quarkus.container-image.labels."org.opencontainers.image.revision"" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo
2024-07-18 14:53:42,089 WARN  [io.qua.config] (Quarkus Main Thread) Unrecognized configuration key …
```
> fix: resolve container-image label and Strimzi API index warnings

- operator/src/main/java/com/github/streamshub/console/ConsoleReconciler.java
This PR is a follow-up which adds more CSV metadata fields. That should improve overall display in Openshift UI and help with search using streams and kafka related keywords.
Result:
>  [Operator] Add more csv fields to improve operator display in Openshift UI 

- operator/src/main/java/com/github/streamshub/console/api/v1alpha1/Console.java
This PR adds CSV metadata to Console Instance card displayed in openshift UI, which currently has "Not available" description.
Signed-off-by: jkalinic <jkalinic@redhat.com>
> [Operator] Add Console Instance Description

- operator/bin/modify-bundle-metadata.sh
Explicitly use UTC time with `Z` zone indicator and `T` date/time delimiter.
https://k8s-operatorhub.github.io/community-operators/packaging-required-fields/
> Use date/time format required by OperatorHub for createdAt

- ui/tests/playwright/BrokerPropertyPage.test.tsx
- ui/tests/playwright/BrokersPage.test.tsx
- ui/tests/playwright/ConsumerGroupsPage.test.tsx
- ui/tests/playwright/ConsumerPage.test.tsx
- ui/tests/playwright/MessagesPage.test.tsx
- ui/tests/playwright/PartitionsPage.test.tsx
- ui/tests/playwright/TopicConsumers.test.tsx
- ui/tests/playwright/playwright.config.ts
This increases the number of retries to deal with flaky tests. All tests pass for me locally, but started failing in GH actions recently. It also removes the waiting for state `networkidle`, which is discouraged [1] and seems to break the tests anyway.
[1] https://playwright.dev/docs/api/class-page#page-wait-for-load-state
> [CI] Increase playwright retries, remove waits for `networkidle` state

- api/src/test/java/com/github/streamshub/console/test/AdminClientSpy.java
Remove unnecessary implementation/delegation of `Admin` calls from `AdminClientSpy`. This avoids future maintenance due to `Admin` API changes, e.g. #1028
> Remove implementation/delegation from AdminClientSpy

- ui/components/Format/DateTime.stories.tsx
- ui/components/MessagesTable/MessagesTable.stories.tsx
- ui/components/MessagesTable/components/MessageDetails.stories.tsx
Use a consistent, fixed date in stories. Avoid unnecessary changes in Chromatic to review
> Use a common, fixed value for storybook date values

- api/src/main/java/com/github/streamshub/console/api/ConsumerGroupsResource.java
- api/src/main/java/com/github/streamshub/console/api/errors/client/JsonProcessingExceptionMapper.java
- api/src/main/java/com/github/streamshub/console/api/service/ConsumerGroupService.java
- api/src/test/java/com/github/streamshub/console/api/ConsumerGroupsResourceIT.java
Implement consumer group patch (reset offsets) "dry run" option required by #960
> Implement consumer group patch (reset offsets) "dry run" option

- ui/app/[locale]/(authorized)/kafka/[kafkaId]/consumer-groups/[groupId]/reset-offset/DryrunSelect.stories.tsx
- ui/app/[locale]/(authorized)/kafka/[kafkaId]/consumer-groups/[groupId]/reset-offset/DryrunSelect.tsx
- ui/app/[locale]/(authorized)/kafka/[kafkaId]/consumer-groups/[groupId]/reset-offset/ResetConsumerOffset.tsx
- ui/app/[locale]/(authorized)/kafka/[kafkaId]/consumer-groups/[groupId]/reset-offset/ResetOffset.stories.tsx
- ui/app/[locale]/(authorized)/kafka/[kafkaId]/consumer-groups/[groupId]/reset-offset/ResetOffset.tsx
- ui/messages/en.json
- Added a dropdown menu with two actions as per the UX team suggestion: "Run and show result" and "Copy dry run command"
- The "Run and show result" action to open the Dryrun page
- The "Copy dry run command" action copies the CLI command to the clipboard
> feat: Add dropdown with actions to run and copy CLI command

- operator/src/main/java/com/github/streamshub/console/dependents/ConsoleIngress.java
Avoid alert `IngressWithoutClassName` on OCP.
> This alert fires when there is an Ingress with an unset IngressClassName for longer than one day.
> Set a default ingressClassName on OpenShift to avoid monitoring alert

- ui/api/kafka/actions.ts
- ui/api/kafka/schema.ts
- ui/app/[locale]/(authorized)/kafka/[kafkaId]/@header/overview/ConnectButton.tsx
- ui/app/[locale]/(authorized)/kafka/[kafkaId]/@header/overview/page.tsx
- ui/app/[locale]/(authorized)/kafka/[kafkaId]/ClusterLinks.tsx
- ui/app/[locale]/(authorized)/kafka/[kafkaId]/layout.tsx
- ui/app/[locale]/(authorized)/kafka/[kafkaId]/overview/ConnectedClusterCard.tsx
- ui/app/[locale]/(authorized)/kafka/[kafkaId]/overview/page.tsx
- ui/app/[locale]/(authorized)/layout.tsx
- ui/components/AppLayout.tsx
- ui/components/ClusterOverview/ClusterCard.stories.tsx
- ui/components/ClusterOverview/ClusterCard.tsx
- ui/components/ClusterOverview/PageLayout.stories.tsx
- ui/components/ClusterOverview/ReconciliationModal.tsx
- ui/components/ReconciliationContext.tsx
- ui/components/ReconciliationPausedBanner.tsx
- ui/components/ReconciliationProvider.tsx
- ui/messages/en.json
feat: pause reconciliation
Design [link](https://www.figma.com/proto/JHubc4ULXXhKAEk8VyaW2f/AMQ-Streams-console?page-id=398%3A9817&node-id=1100-7414&node-type=FRAME&viewport=303%2C-232%2C0.29&t=ufkbHniczdcX05ET-1&scaling=min-zoom&content-scaling=fixed)
> feat: pause reconciliation

- .github/project.yml
The 0.4.0 milestone has over 100 issues accumulated, so this should be a good time to set a new tag. Several feature added in 0.4.0 allow for modifications - reset consumer groups, pause/resume Kafka reconciliation, and maintenance of KafkaRebalance CRs - that will not support authentication until 0.5.0.
> Release 0.4.0

- ui/pom.xml
NPM compares the old and new versions without suffixes, so 0.4.0-SNAPSHOT has the `-SNAPSHOT` trimmed before comparison. This change tells NPM to allow the same version, bypassing the comparison. Ultimately, the version changed in the package*.json files will not be the same.
> Pass `allow-same-version` to npm-version

- api/src/main/java/com/github/streamshub/console/api/service/RecordService.java
- api/src/main/java/com/github/streamshub/console/api/support/serdes/MultiformatDeserializer.java
- Skip consumer assignments for topic partitions with no data
- Skip consumer assignments that seek beyond the end of the assigned topic partition
- Limit consumer poll time to 100ms per request to poll the consumer
- Make total time polling via the endpoint configurable, default 5s
- Fix NPE in multi-format de-serializer
> fix: Improve slow consume records operation

- .github/workflows/playwright-tests.yml
- .github/workflows/release.yml
- Makefile
- README.md
- install/operator-olm/000-OperatorGroup-console-operator.yaml
- install/operator-olm/010-CatalogSource-console-operator-catalog.yaml
- install/operator-olm/020-Subscription-console-operator.yaml
- operator/bin/common.sh
- operator/bin/generate-catalog.sh
- operator/bin/modify-bundle-metadata.sh
- operator/src/main/java/com/github/streamshub/console/LeaderConfiguration.java
- operator/src/main/kubernetes/kubernetes.yml
- operator/src/main/resources/application.properties
This PR targets current generic `console-operator` naming and changes it to `streamshub-operator`. This change affects kubernetes resources like Operator, CSV, Pod, Deployment, but also a ServiceAccount. However this change ignores image names as their full name already contains `streamshub` part in the registry name.
> [OLM] Operator name change

- .github/workflows/integration.yml
- .github/workflows/playwright-tests.yml
- .github/workflows/release.yml
- .github/workflows/snapshot.yml
- Makefile
- operator/bin/common.sh
- operator/bin/generate-catalog.sh
- operator/bin/modify-bundle-metadata.sh
This PR introduces the use of SHA digests for built images in operator environment variables. Instead of relying on image tags, which can be unreliable for snapshot and latest tagged images, the operator now explicitly references UI and API images using their SHA digests.
The API and UI images will now always pull the correct version, ensuring consistency and avoiding issues caused by tag mismatches. 
This change was necessary because previously, using snapshot images with tags could result in the wrong image being pulled due to the console deployment's `IfNotPresent` image pull policy.
> Change image tags with digests in bundle metadata

- ui/components/MessagesTable/components/PartitionSelector.tsx
fixes:Partition 20+ cannot be selected in the message [browser](https://github.com/streamshub/console/issues/1250)
> fix:Partition 20+ cannot be selected in the message browser

- api/src/main/java/com/github/streamshub/console/api/service/TopicService.java
- api/src/test/java/com/github/streamshub/console/api/TopicsResourceIT.java
- api/src/test/java/com/github/streamshub/console/test/TestHelper.java
> fix: check for presence of KafkaTopic status in managed topic lookup

- .github/workflows/integration.yml
- .github/workflows/release.yml
- .github/workflows/snapshot.yml
- Makefile
- operator/bin/generate-catalog.sh
- operator/bin/modify-bundle-metadata.sh
Fixes #1279 
- correct working directory for bundle modifications during release
- make sure `common.sh` is not evaluated before the vars it depends on
- update package name in bundle annotations YAML and container image labels
> fix: correct release failure and incorrect CSV name generation

- ui/app/[locale]/(authorized)/kafka/[kafkaId]/consumer-groups/[groupId]/page.tsx
- ui/app/[locale]/(authorized)/kafka/[kafkaId]/consumer-groups/[groupId]/reset-offset/page.tsx
- ui/app/[locale]/(authorized)/kafka/[kafkaId]/consumer-groups/page.tsx
- ui/app/[locale]/(authorized)/kafka/[kafkaId]/nodes/[nodeId]/configuration/page.tsx
- ui/app/[locale]/(authorized)/kafka/[kafkaId]/nodes/page.tsx
- ui/app/[locale]/(authorized)/kafka/[kafkaId]/nodes/rebalances/page.tsx
- ui/app/[locale]/(authorized)/kafka/[kafkaId]/overview/page.tsx
- ui/app/[locale]/(authorized)/kafka/[kafkaId]/topics/(page)/page.tsx
- ui/app/[locale]/(authorized)/kafka/[kafkaId]/topics/[topicId]/configuration/page.tsx
- ui/app/[locale]/(authorized)/kafka/[kafkaId]/topics/[topicId]/consumer-groups/page.tsx
- ui/app/[locale]/(authorized)/kafka/[kafkaId]/topics/[topicId]/messages/page.tsx
- ui/app/[locale]/(authorized)/kafka/[kafkaId]/topics/[topicId]/partitions/page.tsx
- ui/app/[locale]/(public)/(home)/page.tsx
- ui/app/[locale]/(public)/kafka/[kafkaId]/login/page.tsx
- ui/app/[locale]/layout.tsx
- ui/messages/en.json
Set page titles based on the content. This allows for a more usable browser history. Most of the titles here are not specific to the Kafka or Topic name viewed, which can be added later.
All titles have the format `{page specific name} | StreamsHub console`.
Closes #1210
> Content-specific page titles

- api/src/main/java/com/github/streamshub/console/api/service/MetricsService.java
- api/src/main/java/com/github/streamshub/console/api/support/KafkaContext.java
- api/src/main/java/com/github/streamshub/console/api/support/serdes/ApicurioClient.java
- api/src/main/resources/application.properties
- common/src/main/java/com/github/streamshub/console/support/StringSupport.java
- common/src/test/java/com/github/streamshub/console/support/StringSupportTest.java
- operator/src/main/java/com/github/streamshub/console/api/v1alpha1/spec/SchemaRegistry.java
- operator/src/main/java/com/github/streamshub/console/api/v1alpha1/spec/TrustStore.java
- operator/src/main/java/com/github/streamshub/console/api/v1alpha1/spec/Value.java
- operator/src/main/java/com/github/streamshub/console/api/v1alpha1/spec/ValueReference.java
- operator/src/main/java/com/github/streamshub/console/api/v1alpha1/spec/metrics/MetricsSource.java
- operator/src/main/java/com/github/streamshub/console/dependents/ConsoleDeployment.java
- operator/src/main/java/com/github/streamshub/console/dependents/ConsoleSecret.java
- operator/src/main/resources/com/github/streamshub/console/dependents/console.deployment.yaml
- operator/src/test/java/com/github/streamshub/console/ConsoleReconcilerTest.java
Closes #1277 
--- 
Approach
This change allows for a trust store to be configured for metrics source (Prometheus) and schema registry (Apicurio) clients. The trust store may be set in the Console CR along with the URLs for each connection type.
For example:
```yaml
...
spec:
metricsSources:
- name: ocp-prometheus
type: openshift-monitoring
url: https://thanos-querier.mycluster.example.com
truststore:
type: PEM  # also supports JKS or PKCS12
alias: "" # optional, only for JKS or PKCS12
password: {} # optional, only for JKS or PKCS12. Same structure as `content` below
content:
value: |
-----BEGIN CERTIFICATE-----
MIIFazCCA1OgAwIBAgIRAIIQz7DSQONZRGPgu2OCiwAwDQYJKoZIhvcNAQELBQAw
...
emyPxgcYxn/eR44/KJ4EBs+lVDR3veyJm+kXQ99b21/+jh5Xos1AnX5iItreGCc=
-----END CERTIFICATE-----
valueFrom: …
```
> Configuration of trust stores for Prometheus and Apicurio clients

- .github/workflows/playwright-tests.yml
- examples/kafka/030-Kafka-console-kafka.yaml
Fix failing Playwright tests. Strimzi 0.45 removes support for Kafka 3.7.0
> fix: bump example Kafka version from 3.7.0 to 3.9.0

- ui/app/[locale]/(authorized)/kafka/[kafkaId]/@activeBreadcrumb/consumer-groups/[groupId]/reset-offset/page.tsx
- ui/app/[locale]/(authorized)/kafka/[kafkaId]/@header/consumer-groups/[groupId]/reset-offset/page.tsx
- ui/app/[locale]/(authorized)/kafka/[kafkaId]/consumer-groups/ConsumerGroupsTable.tsx
- ui/app/[locale]/(authorized)/kafka/[kafkaId]/consumer-groups/[groupId]/reset-offset/DryrunSelect.tsx
- ui/app/[locale]/(authorized)/kafka/[kafkaId]/consumer-groups/[groupId]/reset-offset/ResetConsumerOffset.tsx
- ui/app/[locale]/(authorized)/kafka/[kafkaId]/consumer-groups/[groupId]/reset-offset/ResetOffset.tsx
1. **Reset Offset Button Visibility**: Fix an issue where the "Reset Offset" button remains visible while already on the reset offset form. This occurs when navigating from the "Reset Offset" button on the consumer group page (but not when accessed via the list kebab menu).
2. **Remove Description Text in Kebab Menu**: Remove the description text in the kebab menu for consumer groups where the status is empty.
3. **Disable Dryrun Button Until Offset is Selected**: Ensure the "Dryrun" button remains disabled until an offset value is selected.
4. **Restrict Custom Input to Non-Negative Values**: Prevent negative numbers from being entered in the "Custom Offset" input field.
> Bug fix in reset offset page

- ui/app/[locale]/(authorized)/kafka/[kafkaId]/nodes/rebalances/RebalanceTable.tsx
- ui/app/[locale]/(authorized)/kafka/[kafkaId]/nodes/rebalances/page.tsx
- ui/messages/en.json
Added Missing spacing the between expanded row and the table row
Added tooltip text for Status label
Added helper text for Mode header
Removed Duplicate column header
> UX enhancement in Rebalance Page

- api/pom.xml
- api/src/test/java/com/github/streamshub/console/kafka/systemtest/TestPlainProfile.java
- api/src/test/java/com/github/streamshub/console/kafka/systemtest/deployment/ApicurioResourceManager.java
- api/src/test/resources/Dockerfile.apicurio
- pom.xml
- CVE-free version of Nimbus JOSE managed by Quarkus
- Remove use of quarkus-kafka-clients and quarkus-apicurio-registry-avro
- Add Apicurio resource manager and test container to replace dev services previously provided by quarkus-apicurio-registry-avro
> Apicurio Registry direct dependency management, remove Nimbus JOSE mgmt

- Makefile
- Default `PLATFORMS` in Makefile to just the current native platform.
- Use `QUARKUS_DOCKER_ADDITIONAL_ARGS` instead of `QUARKUS_DOCKER_BUILDX_PLATFORM` (does not work with podman)
> fix: default to local platform, use docker additional-args Quarkus flag

- .github/project.yml
Attempt release 0.6.2 again, with debugging for catalog failure. I'm not able to reproduce the failure locally.
> Release 0.6.2 (attempt 2)

- .github/workflows/release.yml
- pom.xml
Set the `container-image` release profile via POM and explicitly disable the `release-preparation` profile with the same mechanism. For some reason, `release-preparation` is activated during `release:perform`, leading to an additional execution of the `operator/bin/release-prepare.sh` script, which generates garbage and fails the release.
> fix: set releaseProfiles via POM, force disable release-preparation

- ui/app/[locale]/(authorized)/kafka/[kafkaId]/overview/ConnectedClusterCard.tsx
fix: Display cluster errors and warnings regardless of metrics availability
Previously, errors and warnings were not shown if metrics were unavailable, which was incorrect.  
This update ensures that errors and warnings are always displayed, irrespective of the presence of metrics.
> Ensure cluster errors and warnings are displayed even when metrics are unavailable

- api/src/main/java/com/github/streamshub/console/api/service/NodeService.java
- ui/api/kafka/schema.ts
- ui/api/nodes/schema.ts
- ui/app/[locale]/(authorized)/kafka/[kafkaId]/@header/nodes/page.tsx
- ui/app/[locale]/(authorized)/kafka/[kafkaId]/@header/nodes/rebalances/page.tsx
- ui/app/[locale]/(authorized)/kafka/[kafkaId]/overview/ConnectedClusterCard.tsx
- ui/app/[locale]/(authorized)/kafka/[kafkaId]/topics/create/page.tsx
Summary includes information for the entire dataset. Also correctly indicate node health/status counts in the header.
> Refine node list summary, based on entries prior to applying filters

- api/src/main/java/com/github/streamshub/console/api/model/Topic.java
- api/src/test/java/com/github/streamshub/console/api/TopicsResourceIT.java
Fixes #147
Note, issue 147 mentions sorting by `recordCount` which is no longer supported and can be ignored.
> fix: include topic size in pagination cursor when sorted by bytes

- api/src/test/java/com/github/streamshub/console/kafka/systemtest/deployment/DeploymentManager.java
- api/src/test/java/com/github/streamshub/console/kafka/systemtest/utils/ConsumerUtils.java
- api/src/test/java/com/github/streamshub/console/test/TopicHelper.java
- api/src/test/resources/Dockerfile.kafka
- pom.xml
* Bump strimzi-test-container to 0.110.0
* Bump Kafka version in API integration tests to 4.0
* Set `group.coordinator.new.enable=false` to still allow blank/empty consumer group ID compatibility
* Make create/delete topic operations in test helpers blocking to ensure topics are fully created or removed
* Make delete consumer group operations in test helpers blocking for same reason
> Update strimzi-test-container to 0.110.0 with Kafka 4.0

- api/src/main/java/com/github/streamshub/console/api/TopicsResource.java
- api/src/main/java/com/github/streamshub/console/api/service/NodeService.java
- api/src/main/java/com/github/streamshub/console/api/service/TopicDescribeService.java
- api/src/main/java/com/github/streamshub/console/api/service/TopicService.java
- api/src/main/java/com/github/streamshub/console/api/support/TopicValidation.java
- api/src/test/java/com/github/streamshub/console/api/TopicsResourceIT.java
- api/src/test/java/com/github/streamshub/console/test/TopicHelper.java
- ui/app/[locale]/(authorized)/kafka/[kafkaId]/topics/[topicId]/configuration/ConfigTable.tsx
- ui/package-lock.json
- ui/package.json
The operations to create, update, and delete topics did not consider whether a Kafka cluster is using the Strimzi Topic Operator (for creation) or whether an existing topic is backed by a Strimzi `KafkaTopic` CR. This change addresses the gap by:
- create a `KafkaTopic` CR during topic creation if the topic entity operator is enabled for a Kafka CR. Otherwise, create directly in Kafka
- update the `KafkaTopic` CR for managed topics, else directly in Kafka
- delete the `KafkaTopic` CR for managed topics, else directly in Kafka
This functionality is not accessible in the UI when read-only mode is enabled.
> fix: properly implement topic mutate operations for KafkaTopic CRs

- ui/app/[locale]/(authorized)/kafka/[kafkaId]/nodes/DistributionChart.stories.tsx
- ui/app/[locale]/(authorized)/kafka/[kafkaId]/nodes/DistributionChart.tsx
- ui/app/[locale]/(authorized)/kafka/[kafkaId]/nodes/page.tsx
- ui/utils/config.ts
Also suppress non-PEM truststore warning when no truststore is configured at all.
With OK statuses:
With warning statuses:
> fix: choose node icon based on aggregate status

- ui/package-lock.json
Same as #1732 for `0.8.4`
Bumps [pbkdf2](https://github.com/crypto-browserify/pbkdf2) from 3.1.2 to 3.1.3.
- [Changelog](https://github.com/browserify/pbkdf2/blob/master/CHANGELOG.md)
- [Commits](https://github.com/crypto-browserify/pbkdf2/compare/v3.1.2...v3.1.3)
---
updated-dependencies:
- dependency-name: pbkdf2 dependency-version: 3.1.3 dependency-type: indirect ...
> build(deps-dev): bump pbkdf2 from 3.1.2 to 3.1.3 in /ui

- systemtests/pom.xml
Since the system tests is separate from the Quarkus applications, it should be better to manage these dependency versions separately from the parent. Especially because this is the only module using Log4J2.
> [ST] Manage and update several dependencies to override Quarkus versions

- operator/src/main/java/com/github/streamshub/console/ConsoleReconciler.java
- operator/src/main/java/com/github/streamshub/console/api/v1alpha1/status/ConsoleStatus.java
- operator/src/main/java/com/github/streamshub/console/dependents/BaseClusterRole.java
- operator/src/main/java/com/github/streamshub/console/dependents/BaseClusterRoleBinding.java
- operator/src/main/java/com/github/streamshub/console/dependents/ConfigurationProcessor.java
- operator/src/test/java/com/github/streamshub/console/ConsoleReconcilerTest.java
- operator/src/test/java/com/github/streamshub/console/ConsoleReconcilerTestBase.java
Fixes #1779 
- Correct the naming of cluster-scoped resources owned by the Console CR to avoid conflicts
- Fix status check of the configuration handler to only consider errors set in the CR's status during the current reconciliation
- Improve the reporting of conditions by checking for resources that encountered exceptions and ignoring the primary exception if already reported by the exceptions of individual resources
> fix: include namespace in cluster-scoped names, refine CR conditions

- operator/src/main/java/com/github/streamshub/console/dependents/ConfigurationProcessor.java
- operator/src/test/java/com/github/streamshub/console/ConsoleReconcilerTest.java
- operator/src/test/java/com/github/streamshub/console/ConsoleReconcilerTestBase.java
The operator currently only supports the use of SCRAM authentication in the Strimzi `KafkaUser` CR. This change adds support for mutual TLS authentication. When detected, the operator will obtain the keystore and truststore from the `KafkaUser`'s secret and configure the Kafka connection accordingly.
Closes #1796
> Add auto-configuration of mTLS Kafka authentication based on KafkaUser

- api/src/main/java/com/github/streamshub/console/api/service/KafkaConnectService.java
- api/src/test/java/com/github/streamshub/console/api/KafkaConnectorsResourceIT.java
Next.js seems to treat the period/decimal point `.` as a special character, causing trouble with routing. This PR updates the Kafka Connect delimiters to use a comma instead.
> fix: use comma as component delimiter for Kafka Connect identifiers

- api/src/main/java/com/github/streamshub/console/api/model/connect/ConnectClusterFilterParams.java
- api/src/main/java/com/github/streamshub/console/api/model/connect/Connector.java
- api/src/main/java/com/github/streamshub/console/api/model/connect/ConnectorFilterParams.java
- api/src/main/java/com/github/streamshub/console/api/model/connect/ConnectorPlugin.java
- api/src/main/java/com/github/streamshub/console/api/service/KafkaConnectService.java
- api/src/main/resources/application.properties
- api/src/test/java/com/github/streamshub/console/api/KafkaConnectorsResourceIT.java
- api/src/test/resources/com/github/streamshub/console/api/KafkaConnect-fixtures.yaml
- common/src/main/java/com/github/streamshub/console/config/ConsoleConfig.java
- common/src/test/java/com/github/streamshub/console/config/ConsoleConfigTest.java
Add the MirrorMaker type to the connector and plugin types when the class of the connector or plugin indicates MirrorMaker (may be overridden via environment variable in cases where a customized class is used). The type may also be filtered so that only MM connectors or only non-MM connectors are returned.
Also validate Kafka Connect name/namespace/mirrorMaker flag combination is unique.
> Include MirrorMaker type in connector type, add filter

- pom.xml
Bumps `quarkus.platform.version` from 3.20.2 to 3.20.2.1.
Updates `io.quarkus.platform:quarkus-bom` from 3.20.2 to 3.20.2.1
- [Commits](https://github.com/quarkusio/quarkus-platform/compare/3.20.2...3.20.2.1)
Updates `io.quarkus.platform:quarkus-operator-sdk-bom` from 3.20.2 to 3.20.2.1
- [Commits](https://github.com/quarkusio/quarkus-platform/compare/3.20.2...3.20.2.1)
Updates `io.quarkus.platform:quarkus-maven-plugin` from 3.20.2 to 3.20.2.1
- [Commits](https://github.com/quarkusio/quarkus-platform/compare/3.20.2...3.20.2.1)
---
updated-dependencies:
- dependency-name: io.quarkus.platform:quarkus-bom dependency-version: 3.20.2.1 dependency-type: direct:production update-type: version-update:semver-patch
- dependency-name: io.quarkus.platform:quarkus-operator-sdk-bom dependency-version: …
> [0.8.x] build(deps): bump quarkus.platform.version from 3.20.2 to 3.20.2.1

- ui/app/[locale]/(authorized)/kafka/[kafkaId]/nodes/rebalances/RebalanceTable.tsx
- ui/components/AppHeader.tsx
- ui/components/ClusterOverview/ClusterCard.tsx
- ui/components/ClusterOverview/PageLayout.tsx
- ui/components/ClusterOverview/components/ChartCpuUsage.tsx
- ui/components/ClusterOverview/components/ChartDiskUsage.tsx
- ui/components/ClusterOverview/components/ChartIncomingOutgoing.tsx
- ui/components/ClusterOverview/components/ChartMemoryUsage.tsx
- ui/components/Format/DateTime.stories.tsx
- ui/components/Format/DateTime.tsx
- ui/components/MessagesTable/MessagesTable.tsx
- ui/components/MessagesTable/components/ColumnsModal.tsx
- ui/components/MessagesTable/components/MessageDetails.tsx
- ui/messages/en.json
- ui/package.json
- ui/utils/dateTime.ts
Currently, the console displays dates in a few different ways:
- User's local time zone in US format (MM/dd/yy)
- UTC time zone in US format (MM/dd/yy)
- UTC time zone in ISO format
The PR standardizes all dates to ISO format and display most dates in the user's time zone. The exception is that the topic message table has the option to display the date/time in UTC.
> fix: use ISO format for all dates, limit UTC to message table

- .github/actions/systemtests/common.sh
- .github/actions/systemtests/parse-results-update-pr.sh
- .github/actions/systemtests/pr-help.sh
- .github/actions/systemtests/update-pr-systemtests-started.sh
- .github/actions/systemtests/verify-workflow-run-succeeded.sh
- .github/workflows/pre-systemtest.yml
- .github/workflows/systemtests.yml
In order to have streamshub-bot comment all the messages related to systemtests actions it's necessary to use either the previous token or create a new one with comment permissions. This PR also fixes HELP comment being replaced by other comments like build started or cannot trigger systemtests, this makes it hard for user to see the help messages. `getEditModeOrSkipIfLastCommentIsHelp` solves this issue by looking at it's last bot comment and returning --edit-last flag if it's not a systemtests help comment.
> [GHA] Add changes
